### ISSUE TITLE
支持IPv6

### ISSUE THREAD

**Issue by Hello-XPH** [xiaobovlog/IPCCReplacer#2]
使用了您的IPCCReplacer 3.0 安装您B站视频操作后发行不能获取到IPv6了，可以解决这个问题吗？大佬。

**Comment by xiaobovlog** [comment]
解除所有锁定，重启几次就会恢复到以前

**Comment by Hello-XPH** [comment]
有没有之前那个之锁定SA的那个版本 BV1sN4y1Y7Vz

**Comment by Hello-XPH** [comment]
@xiaobovlog

**Comment by tsingter** [comment]
那个如果没卡好5G之前，用ipccreplacer会出现什么后果啊？ 是不是会间歇性的不读卡贴啊？

**Comment by Hello-XPH** [comment]
不会吧，实在不行就清除嘛
